!byte $00,$00,$00,$00,$00,$00,$00,$00	; char $ 0 HERE PREV OLD
!byte $80,$c0,$e0,$f0,$f8,$fc,$fe,$ff	; char $ 1      PREV 
!byte $c0,$60,$38,$0e,$18,$30,$1e,$07	; char $ 2      PREV 
!byte $ff,$7f,$3f,$1f,$0f,$07,$03,$01	; char $ 3      PREV 
!byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$80	; char $ 4      PREV 
!byte $00,$18,$3c,$7e,$7e,$3c,$18,$00	; char $ 5      PREV 
!byte $03,$06,$0c,$06,$23,$36,$7c,$c8	; char $ 6      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff	; char $ 7 HERE PREV 
!byte $80,$c0,$60,$30,$1e,$36,$72,$c9	; char $ 8      PREV 
!byte $01,$03,$07,$0f,$1f,$3f,$7f,$ff	; char $ 9      PREV 
!byte $01,$03,$06,$2c,$7c,$86,$ca,$91	; char $ a      PREV 
!byte $aa,$aa,$aa,$bf,$bf,$bf,$bf,$bf	; char $ b      PREV 
!byte $aa,$aa,$aa,$ff,$ff,$ff,$ff,$ff	; char $ c      PREV 
!byte $a9,$a9,$a9,$fd,$fd,$fd,$fd,$fd	; char $ d      PREV 
!byte $bf,$bf,$bf,$bf,$bf,$bf,$bf,$bf	; char $ e      PREV 
!byte $aa,$aa,$aa,$80,$80,$80,$80,$80	; char $ f      PREV 
!byte $aa,$aa,$aa,$00,$00,$00,$00,$00	; char $10      PREV 
!byte $5f,$6f,$6f,$2f,$2f,$2f,$2f,$2f	; char $11      PREV 
!byte $55,$56,$56,$42,$42,$42,$42,$42	; char $12      PREV 
!byte $fa,$fa,$fa,$f8,$f8,$f8,$f8,$f8	; char $13      PREV 
!byte $55,$56,$56,$02,$02,$02,$02,$02	; char $14      PREV 
!byte $fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe	; char $15      PREV 
!byte $80,$80,$80,$80,$80,$80,$80,$80	; char $16      PREV 
!byte $af,$af,$af,$ff,$ff,$ff,$ff,$ff	; char $17      PREV 
!byte $2f,$2f,$2f,$2f,$2f,$2f,$2f,$2f	; char $18      PREV 
!byte $bf,$bf,$bf,$bf,$bf,$aa,$aa,$aa	; char $19      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$5f,$6f,$6f	; char $1a      PREV 
!byte $40,$40,$40,$40,$40,$5a,$6a,$aa	; char $1b      PREV 
!byte $00,$00,$00,$00,$00,$02,$02,$02	; char $1c      PREV 
!byte $2f,$2f,$2f,$2f,$2f,$af,$af,$af	; char $1d      PREV 
!byte $42,$42,$42,$42,$42,$42,$42,$42	; char $1e      PREV 
!byte $f8,$f8,$f8,$f8,$f8,$f8,$f8,$f8	; char $1f      PREV 
!byte $00,$00,$00,$00,$00,$0a,$0a,$0a	; char $20      PREV 
!byte $02,$02,$02,$02,$02,$aa,$aa,$aa	; char $21      PREV 
!byte $00,$00,$00,$00,$00,$a9,$a5,$95	; char $22      PREV 
!byte $02,$02,$02,$02,$02,$02,$02,$02	; char $23      PREV 
!byte $0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b	; char $24      PREV 
!byte $bd,$bd,$bd,$bd,$bd,$bd,$bd,$bd	; char $25      PREV 
!byte $bd,$bd,$bd,$bd,$bd,$a5,$95,$55	; char $26      PREV 
!byte $fe,$fe,$fe,$fe,$fe,$aa,$aa,$aa	; char $27      PREV 
!byte $0b,$0b,$0b,$0b,$0b,$0a,$09,$05	; char $28      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$55,$56,$56	; char $29      PREV 
!byte $40,$40,$40,$40,$40,$6a,$6a,$aa	; char $2a      PREV 
!byte $00,$00,$00,$00,$00,$aa,$aa,$aa	; char $2b      PREV 
!byte $42,$42,$42,$42,$42,$6a,$6a,$aa	; char $2c      PREV 
!byte $f4,$f4,$f4,$f4,$f4,$f6,$f6,$fa	; char $2d      PREV 
!byte $bf,$bf,$bf,$bf,$bf,$55,$55,$55	; char $2e      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$aa,$aa,$aa	; char $2f      PREV 
!byte $00,$01,$03,$07,$0f,$1f,$3f,$7f	; char $30      PREV 
!byte $7f,$7f,$7f,$7f,$7f,$7f,$7f,$7f	; char $31      PREV 
!byte $7f,$3f,$1f,$0f,$0f,$1f,$3f,$7f	; char $32      PREV 
!byte $0f,$0f,$0f,$0f,$0f,$0f,$0f,$0f	; char $33      PREV 
!byte $80,$c0,$e0,$f0,$f0,$e0,$c0,$80	; char $34      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$ef,$cf,$8f	; char $35      PREV 
!byte $7f,$3f,$1f,$0f,$07,$03,$01,$00	; char $36 HERE PREV 
!byte $7f,$7f,$7e,$7c,$78,$70,$60,$40	; char $37      PREV 
!byte $ff,$ff,$7f,$3f,$1f,$0f,$07,$03	; char $38      PREV 
!byte $0f,$0f,$0f,$0f,$0f,$0e,$0c,$08	; char $39      PREV 
!byte $fe,$fc,$f8,$f0,$e0,$c0,$80,$00	; char $3a      PREV 
!byte $55,$55,$55,$55,$55,$55,$55,$55	; char $3b HERE      
!byte $55,$55,$55,$55,$57,$5f,$7f,$ff	; char $3c HERE      
!byte $57,$5f,$7f,$ff,$ff,$ff,$ff,$ff	; char $3d HERE      
!byte $f5,$fd,$fb,$d8,$e8,$d8,$ea,$da	; char $3e HERE      
!byte $55,$55,$55,$55,$d5,$f5,$fd,$ff	; char $3f HERE      
!byte $d5,$f5,$fd,$ff,$ff,$ff,$ff,$ff	; char $40 HERE      
!byte $ea,$da,$ea,$da,$ea,$da,$ea,$da	; char $41 HERE      
!byte $00,$00,$24,$18,$18,$24,$00,$00	; char $42 HERE      
!byte $00,$00,$00,$00,$00,$00,$00,$01	; char $43 HERE      
!byte $00,$00,$00,$00,$00,$00,$7c,$fe	; char $44 HERE      
!byte $03,$07,$0e,$1c,$38,$33,$71,$60	; char $45 HERE      
!byte $e7,$99,$3c,$3c,$3c,$18,$81,$db	; char $46 HERE      
!byte $80,$c0,$e0,$70,$78,$fc,$ee,$c6	; char $47 HERE      
!byte $60,$e0,$c0,$c0,$c0,$c0,$e1,$63	; char $48 HERE      
!byte $7f,$3f,$2e,$3c,$7c,$fc,$e6,$c3	; char $49 HERE      
!byte $86,$07,$03,$03,$03,$03,$06,$06	; char $4a HERE      
!byte $67,$3f,$3e,$1c,$0e,$07,$03,$00	; char $4b HERE      
!byte $c3,$c3,$c3,$c3,$c3,$00,$c3,$ff	; char $4c HERE      
!byte $06,$0c,$1c,$38,$70,$e0,$c0,$00	; char $4d HERE      
!byte $3c,$00,$00,$00,$00,$00,$00,$00	; char $4e HERE      
!byte $fd,$dd,$d5,$d0,$58,$aa,$a8,$a0	; char $4f HERE      
!byte $ff,$7f,$5d,$00,$00,$00,$00,$00	; char $50 HERE      
!byte $ff,$ff,$55,$02,$01,$02,$01,$02	; char $51 HERE      
!byte $fd,$dd,$d5,$d1,$51,$00,$00,$00	; char $52 HERE      
!byte $00,$00,$ab,$ab,$ab,$ab,$00,$00	; char $53 HERE      
!byte $3f,$0f,$0f,$0f,$1f,$0b,$00,$02	; char $54 HERE      
!byte $00,$3e,$73,$61,$61,$73,$3e,$00	; char $55 HERE      
!byte $ff,$ff,$ff,$ff,$bf,$af,$ab,$aa	; char $56 HERE      
!byte $ff,$ff,$ff,$ff,$fe,$fa,$ea,$aa	; char $57 HERE      
!byte $00,$c0,$f0,$fc,$ff,$ff,$ff,$ff	; char $58 HERE      
!byte $80,$41,$80,$41,$80,$41,$80,$41	; char $59 HERE      
!byte $ff,$ff,$ff,$ff,$ff,$fd,$f4,$d0	; char $5a HERE      
!byte $ff,$ff,$ff,$ff,$55,$01,$05,$01	; char $5b HERE      
!byte $3f,$0f,$0f,$0f,$1f,$09,$00,$02	; char $5c HERE      
!byte $ff,$fd,$f4,$d0,$40,$00,$00,$00	; char $5d HERE      
!byte $40,$00,$00,$00,$01,$07,$1f,$7f	; char $5e HERE      
!byte $01,$07,$1f,$7f,$ff,$ff,$ff,$ff	; char $5f HERE      
!byte $38,$44,$9a,$ad,$bd,$9a,$82,$82	; char $60 HERE      
!byte $3f,$40,$98,$ac,$bc,$98,$40,$3f	; char $61 HERE      
!byte $ff,$00,$00,$00,$00,$00,$00,$ff	; char $62 HERE      
!byte $ff,$08,$08,$0f,$04,$07,$04,$ff	; char $63 HERE      
!byte $82,$82,$82,$82,$82,$82,$82,$82	; char $64 HERE      
!byte $c0,$d5,$c0,$d9,$d9,$c0,$d5,$c0	; char $65 HERE      
!byte $00,$ff,$00,$6d,$6d,$00,$ff,$00	; char $66 HERE      
!byte $00,$ff,$00,$db,$db,$00,$ff,$00	; char $67 HERE      
!byte $82,$82,$92,$92,$ba,$aa,$aa,$ee	; char $68 HERE      
