!byte $00,$00,$00,$00,$00,$00,$00,$00	; char $ 0 HERE PREV OLD
!byte $80,$c0,$e0,$f0,$f8,$fc,$fe,$ff	; char $ 1 HERE      OLD
!byte $bb,$99,$99,$ff,$bb,$99,$99,$ff	; char $ 2 HERE      OLD
!byte $01,$02,$04,$08,$10,$20,$40,$80	; char $ 3 HERE      OLD
!byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$80	; char $ 4 HERE      OLD
!byte $ab,$af,$bf,$ff,$bf,$af,$ab,$aa	; char $ 5 HERE      OLD
!byte $ff,$ff,$fe,$fb,$be,$bb,$ee,$ba	; char $ 6 HERE      OLD
!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff	; char $ 7 HERE PREV OLD
!byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$ff	; char $ 8 HERE      OLD
!byte $01,$03,$07,$0f,$1f,$3f,$7f,$ff	; char $ 9 HERE      OLD
!byte $00,$00,$00,$00,$00,$00,$00,$ff	; char $ a HERE      OLD
!byte $01,$03,$03,$13,$32,$30,$30,$20	; char $ b HERE      OLD
!byte $aa,$ea,$fa,$fe,$ff,$fe,$fa,$ea	; char $ c HERE      OLD
!byte $80,$80,$80,$80,$be,$9c,$9c,$9c	; char $ d HERE      OLD
!byte $00,$00,$00,$00,$3e,$1c,$1c,$1c	; char $ e HERE      OLD
!byte $81,$83,$83,$93,$b2,$b0,$b0,$a0	; char $ f HERE      OLD
!byte $9a,$9a,$9a,$5a,$5a,$5a,$5a,$5a	; char $10 HERE      OLD
!byte $9a,$9a,$5a,$5a,$5a,$5a,$5a,$5a	; char $11 HERE      OLD
!byte $aa,$aa,$aa,$aa,$aa,$ab,$af,$bf	; char $12 HERE      OLD
!byte $aa,$ab,$af,$bf,$ff,$ff,$ff,$ff	; char $13 HERE      OLD
!byte $01,$02,$04,$08,$10,$20,$40,$ff	; char $14 HERE      OLD
!byte $ff,$80,$80,$80,$80,$80,$80,$80	; char $15 HERE      OLD
!byte $80,$80,$80,$80,$80,$80,$80,$80	; char $16 HERE      OLD
!byte $5a,$5a,$5a,$5a,$5a,$5a,$5a,$5a	; char $17 HERE      OLD
!byte $80,$80,$80,$80,$80,$80,$80,$ff	; char $18 HERE      OLD
!byte $55,$55,$15,$15,$15,$51,$51,$51	; char $19 HERE      OLD
!byte $76,$25,$25,$04,$04,$54,$55,$75	; char $1a HERE      OLD
!byte $db,$4b,$4b,$43,$43,$53,$53,$5b	; char $1b HERE      OLD
!byte $ff,$af,$2f,$5f,$af,$9f,$af,$bf	; char $1c HERE      OLD
!byte $ab,$8b,$97,$ab,$a3,$eb,$8b,$ab	; char $1d HERE      OLD
!byte $ff,$ea,$e2,$e5,$ea,$f8,$e2,$ea	; char $1e HERE      OLD
!byte $ff,$fa,$f8,$f9,$fa,$fa,$fe,$fa	; char $1f HERE      OLD
!byte $ff,$be,$be,$7e,$bf,$3e,$be,$be	; char $20 HERE      OLD
!byte $ff,$bf,$bf,$8f,$cf,$ef,$ef,$eb	; char $21 HERE      OLD
!byte $ab,$ab,$ef,$ef,$ef,$ef,$ef,$eb	; char $22 HERE      OLD
!byte $ea,$ea,$ea,$fb,$fb,$ce,$ef,$eb	; char $23 HERE      OLD
!byte $f8,$fa,$fa,$fa,$ee,$ce,$ef,$eb	; char $24 HERE      OLD
!byte $be,$be,$bb,$fb,$fb,$ba,$ff,$ff	; char $25 HERE      OLD
!byte $84,$3c,$3c,$3c,$3c,$3c,$3c,$84	; char $26 HERE      OLD
!byte $81,$e7,$e7,$e7,$e7,$e7,$e7,$e7	; char $27 HERE      OLD
!byte $33,$33,$33,$83,$f3,$33,$33,$87	; char $28 HERE      OLD
!byte $ff,$03,$05,$09,$11,$21,$41,$81	; char $29 HERE      OLD
!byte $bf,$af,$ab,$aa,$aa,$aa,$aa,$aa	; char $2a HERE      OLD
!byte $fe,$fa,$ea,$aa,$aa,$aa,$aa,$aa	; char $2b HERE      OLD
!byte $81,$81,$81,$81,$81,$81,$81,$81	; char $2c HERE      OLD
!byte $80,$00,$be,$be,$9c,$9c,$9c,$80	; char $2d HERE      OLD
!byte $aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa	; char $2e HERE      OLD
!byte $ff,$00,$00,$00,$00,$00,$00,$00	; char $2f HERE      OLD
!byte $01,$01,$01,$01,$01,$01,$01,$01	; char $30 HERE      OLD
!byte $7f,$7f,$7f,$7f,$7f,$7f,$7f,$7f	; char $31           OLD
!byte $7f,$3f,$1f,$0f,$0f,$1f,$3f,$7f	; char $32           OLD
!byte $0f,$0f,$0f,$0f,$0f,$0f,$0f,$0f	; char $33           OLD
!byte $80,$c0,$e0,$f0,$f0,$e0,$c0,$80	; char $34           OLD
!byte $ff,$ff,$ff,$ff,$ff,$ef,$cf,$8f	; char $35           OLD
!byte $7f,$3f,$1f,$0f,$07,$03,$01,$00	; char $36      PREV OLD
!byte $7f,$7f,$7e,$7c,$78,$70,$60,$40	; char $37           OLD
!byte $ff,$ff,$7f,$3f,$1f,$0f,$07,$03	; char $38           OLD
!byte $0f,$0f,$0f,$0f,$0f,$0e,$0c,$08	; char $39           OLD
!byte $fe,$fc,$f8,$f0,$e0,$c0,$80,$00	; char $3a           OLD
!byte $55,$55,$55,$55,$55,$55,$55,$55	; char $3b      PREV 
!byte $55,$55,$55,$55,$57,$5f,$7f,$ff	; char $3c      PREV 
!byte $57,$5f,$7f,$ff,$ff,$ff,$ff,$ff	; char $3d      PREV 
!byte $f5,$fd,$fb,$d8,$e8,$d8,$ea,$da	; char $3e      PREV 
!byte $55,$55,$55,$55,$d5,$f5,$fd,$ff	; char $3f      PREV 
!byte $d5,$f5,$fd,$ff,$ff,$ff,$ff,$ff	; char $40      PREV 
!byte $ea,$da,$ea,$da,$ea,$da,$ea,$da	; char $41      PREV 
!byte $00,$00,$24,$18,$18,$24,$00,$00	; char $42      PREV 
!byte $00,$00,$00,$00,$00,$00,$00,$01	; char $43      PREV 
!byte $00,$00,$00,$00,$00,$00,$7c,$fe	; char $44      PREV 
!byte $03,$07,$0e,$1c,$38,$33,$71,$60	; char $45      PREV 
!byte $e7,$99,$3c,$3c,$3c,$18,$81,$db	; char $46      PREV 
!byte $80,$c0,$e0,$70,$78,$fc,$ee,$c6	; char $47      PREV 
!byte $60,$e0,$c0,$c0,$c0,$c0,$e1,$63	; char $48      PREV 
!byte $7f,$3f,$2e,$3c,$7c,$fc,$e6,$c3	; char $49      PREV 
!byte $86,$07,$03,$03,$03,$03,$06,$06	; char $4a      PREV 
!byte $67,$3f,$3e,$1c,$0e,$07,$03,$00	; char $4b      PREV 
!byte $c3,$c3,$c3,$c3,$c3,$00,$c3,$ff	; char $4c      PREV 
!byte $06,$0c,$1c,$38,$70,$e0,$c0,$00	; char $4d      PREV 
!byte $3c,$00,$00,$00,$00,$00,$00,$00	; char $4e      PREV 
!byte $fd,$dd,$d5,$d0,$58,$aa,$a8,$a0	; char $4f      PREV 
!byte $ff,$7f,$5d,$00,$00,$00,$00,$00	; char $50      PREV 
!byte $ff,$ff,$55,$02,$01,$02,$01,$02	; char $51      PREV 
!byte $fd,$dd,$d5,$d1,$51,$00,$00,$00	; char $52      PREV 
!byte $00,$00,$ab,$ab,$ab,$ab,$00,$00	; char $53      PREV 
!byte $3f,$0f,$0f,$0f,$1f,$0b,$00,$02	; char $54      PREV 
!byte $00,$3e,$73,$61,$61,$73,$3e,$00	; char $55      PREV 
!byte $ff,$ff,$ff,$ff,$bf,$af,$ab,$aa	; char $56      PREV 
!byte $ff,$ff,$ff,$ff,$fe,$fa,$ea,$aa	; char $57      PREV 
!byte $00,$c0,$f0,$fc,$ff,$ff,$ff,$ff	; char $58      PREV 
!byte $80,$41,$80,$41,$80,$41,$80,$41	; char $59      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$fd,$f4,$d0	; char $5a      PREV 
!byte $ff,$ff,$ff,$ff,$55,$01,$05,$01	; char $5b      PREV 
!byte $3f,$0f,$0f,$0f,$1f,$09,$00,$02	; char $5c      PREV 
!byte $ff,$fd,$f4,$d0,$40,$00,$00,$00	; char $5d      PREV 
!byte $40,$00,$00,$00,$01,$07,$1f,$7f	; char $5e      PREV 
!byte $01,$07,$1f,$7f,$ff,$ff,$ff,$ff	; char $5f      PREV 
!byte $38,$44,$9a,$ad,$bd,$9a,$82,$82	; char $60      PREV 
!byte $3f,$40,$98,$ac,$bc,$98,$40,$3f	; char $61      PREV 
!byte $ff,$00,$00,$00,$00,$00,$00,$ff	; char $62 HERE PREV 
!byte $ff,$08,$08,$0f,$04,$07,$04,$ff	; char $63      PREV 
!byte $82,$82,$82,$82,$82,$82,$82,$82	; char $64      PREV 
!byte $c0,$d5,$c0,$d9,$d9,$c0,$d5,$c0	; char $65      PREV 
!byte $00,$ff,$00,$6d,$6d,$00,$ff,$00	; char $66      PREV 
!byte $00,$ff,$00,$db,$db,$00,$ff,$00	; char $67      PREV 
!byte $82,$82,$92,$92,$ba,$aa,$aa,$ee	; char $68      PREV 
