!byte $00,$00,$00,$00,$00,$00,$00,$00	; char $ 0 HERE      OLD
!byte $00,$00,$00,$00,$00,$00,$00,$80	; char $ 1 HERE      
!byte $20,$20,$b8,$20,$20,$30,$30,$30	; char $ 2 HERE      
!byte $00,$00,$00,$00,$00,$00,$80,$aa	; char $ 3 HERE      
!byte $00,$02,$02,$0a,$02,$02,$03,$03	; char $ 4 HERE      
!byte $00,$00,$0e,$0f,$0e,$0e,$0e,$0f	; char $ 5 HERE      
!byte $0a,$aa,$aa,$aa,$aa,$aa,$aa,$aa	; char $ 6 HERE      
!byte $80,$80,$80,$80,$80,$80,$80,$80	; char $ 7 HERE      
!byte $32,$32,$38,$3a,$38,$3a,$38,$3a	; char $ 8 HERE      
!byte $aa,$aa,$aa,$aa,$a5,$a5,$a9,$aa	; char $ 9 HERE      
!byte $a0,$aa,$aa,$aa,$aa,$6a,$69,$a5	; char $ a HERE      
!byte $00,$00,$a0,$a0,$a0,$a0,$60,$a0	; char $ b HERE      
!byte $0e,$0e,$0e,$0f,$0e,$0e,$0e,$0f	; char $ c HERE      
!byte $aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa	; char $ d HERE      
!byte $b8,$ba,$b8,$ba,$b8,$ba,$b8,$ba	; char $ e HERE      
!byte $af,$a7,$a7,$a7,$a7,$a7,$a7,$27	; char $ f HERE      
!byte $aa,$eb,$e7,$a7,$a7,$a7,$e7,$e7	; char $10 HERE      
!byte $a0,$e0,$e0,$a0,$a0,$a0,$e0,$e0	; char $11 HERE      
!byte $0e,$0f,$0e,$0e,$0e,$0f,$0f,$03	; char $12 HERE      
!byte $aa,$aa,$aa,$aa,$aa,$0a,$00,$00	; char $13 HERE      
!byte $80,$80,$80,$80,$80,$80,$00,$00	; char $14 HERE      
!byte $9a,$9a,$96,$96,$96,$96,$a6,$9a	; char $15 HERE      
!byte $a5,$25,$aa,$2a,$aa,$2a,$a9,$29	; char $16 HERE      
!byte $65,$65,$aa,$aa,$aa,$9a,$99,$99	; char $17 HERE      
!byte $60,$60,$a0,$a0,$a0,$a0,$a0,$a0	; char $18 HERE      
!byte $3b,$2b,$2b,$2b,$ea,$ea,$fa,$fe	; char $19 HERE      
!byte $96,$aa,$a6,$aa,$aa,$aa,$aa,$aa	; char $1a HERE      
!byte $a9,$29,$a9,$29,$aa,$2a,$aa,$2a	; char $1b HERE      
!byte $99,$99,$99,$aa,$aa,$aa,$aa,$a5	; char $1c HERE      
!byte $a0,$a0,$a0,$a0,$a0,$a0,$a0,$50	; char $1d HERE      
!byte $00,$02,$02,$0a,$0a,$2a,$2a,$aa	; char $1e HERE      
!byte $af,$aa,$aa,$aa,$ae,$af,$af,$be	; char $1f HERE      
!byte $2a,$29,$29,$29,$25,$25,$15,$15	; char $20 HERE      
!byte $55,$55,$55,$55,$55,$57,$5d,$77	; char $21 HERE      
!byte $55,$55,$55,$55,$55,$55,$d4,$40	; char $22 HERE      
!byte $50,$52,$52,$5a,$5a,$6a,$2a,$aa	; char $23 HERE      
!byte $aa,$aa,$aa,$aa,$ab,$ab,$af,$af	; char $24 HERE      
!byte $b2,$b2,$f2,$f2,$c2,$c2,$02,$02	; char $25 HERE      
!byte $00,$00,$00,$00,$00,$00,$0a,$aa	; char $26 HERE      
!byte $5d,$77,$5f,$7f,$5f,$7f,$5f,$7f	; char $27 HERE      
!byte $c0,$c2,$c2,$c2,$ea,$ea,$ea,$ea	; char $28 HERE      
!byte $aa,$aa,$aa,$aa,$aa,$aa,$ab,$ab	; char $29 HERE      
!byte $af,$bc,$bc,$bc,$f0,$f0,$f0,$c0	; char $2a HERE      
!byte $02,$02,$02,$02,$02,$02,$02,$02	; char $2b HERE      
!byte $00,$00,$00,$02,$02,$0a,$0a,$0a	; char $2c HERE      
!byte $aa,$aa,$aa,$6a,$6a,$9a,$9a,$9a	; char $2d HERE      
!byte $bf,$af,$aa,$aa,$aa,$aa,$aa,$aa	; char $2e HERE      
!byte $ea,$aa,$aa,$aa,$aa,$aa,$aa,$aa	; char $2f HERE      
!byte $ab,$af,$af,$bf,$bc,$bc,$fc,$f0	; char $30 HERE      
!byte $c0,$00,$00,$00,$00,$00,$00,$00	; char $31 HERE      
!byte $02,$02,$02,$02,$00,$03,$00,$00	; char $32 HERE      
!byte $00,$c0,$00,$80,$80,$80,$80,$80	; char $33 HERE      
!byte $2a,$2a,$2a,$aa,$aa,$aa,$a9,$a9	; char $34 HERE      
!byte $ae,$af,$af,$af,$6f,$5e,$7e,$9e	; char $35 HERE      
!byte $aa,$aa,$fa,$bf,$bb,$fb,$fb,$ef	; char $36 HERE      
!byte $ab,$af,$bb,$fb,$be,$be,$bf,$ef	; char $37 HERE      
!byte $f0,$c0,$c0,$c0,$c0,$c0,$c0,$c0	; char $38 HERE      
!byte $a9,$a9,$a5,$a6,$a5,$a6,$99,$96	; char $39 HERE      
!byte $7f,$9f,$7f,$df,$7f,$df,$7f,$df	; char $3a HERE      
!byte $ef,$ff,$ff,$ff,$ff,$ff,$ff,$ff	; char $3b HERE      
!byte $c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0	; char $3c HERE      
!byte $58,$54,$a4,$a8,$a8,$a8,$a8,$aa	; char $3d HERE      
!byte $7f,$df,$7f,$df,$7f,$df,$7f,$df	; char $3e HERE      
!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff	; char $3f HERE      
!byte $c0,$c0,$c0,$c0,$c0,$00,$00,$00	; char $40 HERE      
!byte $aa,$aa,$aa,$aa,$6a,$6a,$2a,$2a	; char $41 HERE      
!byte $3f,$1f,$3f,$9f,$bf,$9f,$bd,$ad	; char $42 HERE      
!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$7f	; char $43 HERE      
!byte $1a,$1a,$0a,$0a,$0a,$06,$06,$02	; char $44 HERE      
!byte $a5,$a5,$a5,$a7,$a7,$97,$97,$95	; char $45 HERE      
!byte $7f,$7f,$7f,$ff,$ff,$ff,$ff,$7f	; char $46 HERE      
!byte $02,$01,$01,$00,$00,$00,$00,$00	; char $47 HERE      
!byte $95,$95,$95,$b5,$3f,$3f,$3f,$3f	; char $48 HERE      
!byte $7f,$7f,$7f,$7f,$ff,$ff,$ff,$ff	; char $49 HERE      
!byte $ea,$fa,$fa,$fa,$fa,$fa,$fa,$fa	; char $4a HERE      
!byte $ff,$af,$a2,$ae,$af,$af,$af,$af	; char $4b HERE      
!byte $fa,$aa,$aa,$aa,$aa,$ea,$fa,$fe	; char $4c HERE      
!byte $00,$80,$a0,$a8,$aa,$aa,$aa,$aa	; char $4d HERE      
!byte $00,$00,$00,$00,$00,$80,$a0,$a8	; char $4e HERE      
!byte $fa,$fa,$fa,$fa,$fa,$3a,$3a,$3a	; char $4f HERE      
!byte $af,$af,$a3,$a0,$a0,$a0,$a0,$a0	; char $50 HERE      
!byte $ff,$ff,$ff,$ff,$3f,$0f,$0f,$03	; char $51 HERE      
!byte $aa,$ea,$fa,$fe,$ff,$ff,$fd,$fd	; char $52 HERE      
!byte $aa,$aa,$aa,$a5,$95,$5f,$7f,$5f	; char $53 HERE      
!byte $00,$80,$40,$40,$c0,$c0,$c0,$c0	; char $54 HERE      
!byte $3a,$3e,$3e,$3e,$3e,$3e,$0e,$0e	; char $55 HERE      
!byte $a0,$a8,$a8,$a8,$a8,$a8,$a8,$a8	; char $56 HERE      
!byte $03,$00,$00,$00,$00,$00,$00,$00	; char $57 HERE      
!byte $fd,$fd,$fd,$3d,$3f,$0f,$0f,$03	; char $58 HERE      
!byte $5f,$55,$55,$5a,$6a,$ea,$ea,$ea	; char $59 HERE      
!byte $40,$40,$80,$80,$80,$80,$80,$80	; char $5a HERE      
!byte $0e,$0e,$0e,$0e,$0e,$0e,$3e,$3e	; char $5b HERE      
!byte $a8,$a8,$a8,$a8,$a8,$a8,$a8,$a8	; char $5c HERE      
!byte $03,$00,$03,$03,$03,$03,$03,$03	; char $5d HERE      
!byte $ea,$ea,$ea,$ea,$ea,$ea,$ea,$ea	; char $5e HERE      
!byte $00,$00,$03,$03,$0f,$0f,$3f,$3f	; char $5f HERE      
!byte $fe,$fe,$fd,$fd,$fe,$f6,$e5,$a9	; char $60 HERE      
!byte $a8,$a8,$68,$58,$94,$a4,$a8,$68	; char $61 HERE      
!byte $03,$03,$03,$03,$0f,$0f,$0f,$0f	; char $62 HERE      
