!byte $00,$00,$00,$00,$00,$00,$00,$00	; char $ 0 HERE PREV OLD
!byte $80,$c0,$e0,$f0,$f8,$fc,$fe,$ff	; char $ 1      PREV OLD
!byte $bb,$99,$99,$ff,$bb,$99,$99,$ff	; char $ 2      PREV OLD
!byte $01,$02,$04,$08,$10,$20,$40,$80	; char $ 3      PREV OLD
!byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$80	; char $ 4      PREV OLD
!byte $ab,$af,$bf,$ff,$bf,$af,$ab,$aa	; char $ 5      PREV OLD
!byte $ff,$ff,$fe,$fb,$be,$bb,$ee,$ba	; char $ 6      PREV OLD
!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff	; char $ 7      PREV OLD
!byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$ff	; char $ 8      PREV OLD
!byte $01,$03,$07,$0f,$1f,$3f,$7f,$ff	; char $ 9      PREV OLD
!byte $00,$00,$00,$00,$00,$00,$00,$ff	; char $ a      PREV OLD
!byte $01,$03,$03,$13,$32,$30,$30,$20	; char $ b      PREV OLD
!byte $aa,$ea,$fa,$fe,$ff,$fe,$fa,$ea	; char $ c      PREV OLD
!byte $80,$80,$80,$80,$be,$9c,$9c,$9c	; char $ d      PREV OLD
!byte $00,$00,$00,$00,$3e,$1c,$1c,$1c	; char $ e      PREV OLD
!byte $81,$83,$83,$93,$b2,$b0,$b0,$a0	; char $ f      PREV OLD
!byte $9a,$9a,$9a,$5a,$5a,$5a,$5a,$5a	; char $10      PREV OLD
!byte $9a,$9a,$5a,$5a,$5a,$5a,$5a,$5a	; char $11      PREV OLD
!byte $aa,$aa,$aa,$aa,$aa,$ab,$af,$bf	; char $12      PREV OLD
!byte $aa,$ab,$af,$bf,$ff,$ff,$ff,$ff	; char $13      PREV OLD
!byte $01,$02,$04,$08,$10,$20,$40,$ff	; char $14      PREV OLD
!byte $ff,$80,$80,$80,$80,$80,$80,$80	; char $15      PREV OLD
!byte $80,$80,$80,$80,$80,$80,$80,$80	; char $16      PREV OLD
!byte $5a,$5a,$5a,$5a,$5a,$5a,$5a,$5a	; char $17      PREV OLD
!byte $80,$80,$80,$80,$80,$80,$80,$ff	; char $18      PREV OLD
!byte $55,$55,$15,$15,$15,$51,$51,$51	; char $19      PREV OLD
!byte $76,$25,$25,$04,$04,$54,$55,$75	; char $1a      PREV OLD
!byte $db,$4b,$4b,$43,$43,$53,$53,$5b	; char $1b      PREV OLD
!byte $ff,$af,$2f,$5f,$af,$9f,$af,$bf	; char $1c      PREV OLD
!byte $ab,$8b,$97,$ab,$a3,$eb,$8b,$ab	; char $1d      PREV OLD
!byte $ff,$ea,$e2,$e5,$ea,$f8,$e2,$ea	; char $1e      PREV OLD
!byte $ff,$fa,$f8,$f9,$fa,$fa,$fe,$fa	; char $1f      PREV OLD
!byte $ff,$be,$be,$7e,$bf,$3e,$be,$be	; char $20      PREV OLD
!byte $ff,$bf,$bf,$8f,$cf,$ef,$ef,$eb	; char $21      PREV OLD
!byte $ab,$ab,$ef,$ef,$ef,$ef,$ef,$eb	; char $22      PREV OLD
!byte $ea,$ea,$ea,$fb,$fb,$ce,$ef,$eb	; char $23      PREV OLD
!byte $f8,$fa,$fa,$fa,$ee,$ce,$ef,$eb	; char $24      PREV OLD
!byte $be,$be,$bb,$fb,$fb,$ba,$ff,$ff	; char $25      PREV OLD
!byte $84,$3c,$3c,$3c,$3c,$3c,$3c,$84	; char $26      PREV OLD
!byte $81,$e7,$e7,$e7,$e7,$e7,$e7,$e7	; char $27      PREV OLD
!byte $33,$33,$33,$83,$f3,$33,$33,$87	; char $28      PREV OLD
!byte $ff,$03,$05,$09,$11,$21,$41,$81	; char $29      PREV OLD
!byte $bf,$af,$ab,$aa,$aa,$aa,$aa,$aa	; char $2a      PREV OLD
!byte $fe,$fa,$ea,$aa,$aa,$aa,$aa,$aa	; char $2b      PREV OLD
!byte $81,$81,$81,$81,$81,$81,$81,$81	; char $2c      PREV OLD
!byte $80,$00,$be,$be,$9c,$9c,$9c,$80	; char $2d      PREV OLD
!byte $aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa	; char $2e HERE PREV OLD
!byte $ff,$00,$00,$00,$00,$00,$00,$00	; char $2f      PREV OLD
!byte $01,$01,$01,$01,$01,$01,$01,$01	; char $30      PREV OLD
!byte $00,$03,$0e,$0b,$2e,$3a,$2e,$3a	; char $31 HERE      OLD
!byte $ee,$ba,$ea,$aa,$aa,$aa,$a5,$95	; char $32 HERE      OLD
!byte $ee,$aa,$aa,$aa,$aa,$aa,$aa,$69	; char $33 HERE      OLD
!byte $ee,$bb,$ae,$ab,$ae,$ab,$5a,$57	; char $34 HERE      OLD
!byte $00,$80,$e0,$b0,$ec,$b8,$ec,$b8	; char $35 HERE      OLD
!byte $6a,$6a,$6a,$5a,$6a,$6a,$5a,$6a	; char $36 HERE      OLD
!byte $a9,$be,$ff,$f7,$f7,$f7,$be,$aa	; char $37 HERE      OLD
!byte $55,$96,$96,$aa,$aa,$aa,$aa,$aa	; char $38 HERE      OLD
!byte $6a,$be,$ff,$f7,$f7,$f7,$be,$aa	; char $39 HERE      OLD
!byte $a9,$aa,$a9,$aa,$a9,$aa,$a9,$a6	; char $3a HERE      OLD
!byte $55,$55,$55,$55,$55,$55,$55,$55	; char $3b HERE      OLD
!byte $5a,$66,$5a,$16,$19,$06,$01,$00	; char $3c HERE      OLD
!byte $aa,$a9,$a7,$a7,$a7,$69,$9a,$66	; char $3d HERE      OLD
!byte $55,$77,$77,$77,$77,$77,$55,$aa	; char $3e HERE      OLD
!byte $aa,$6a,$da,$da,$da,$6a,$a9,$a5	; char $3f HERE      OLD
!byte $a8,$a4,$98,$a4,$90,$50,$40,$00	; char $40 HERE      OLD
!byte $00,$00,$01,$01,$05,$05,$1d,$1d	; char $41 HERE      OLD
!byte $77,$dd,$77,$dd,$77,$dd,$77,$dd	; char $42 HERE      OLD
!byte $55,$59,$66,$99,$66,$99,$6a,$a9	; char $43 HERE      OLD
!byte $00,$00,$40,$40,$50,$50,$74,$74	; char $44 HERE      OLD
!byte $08,$08,$08,$08,$0a,$0a,$0a,$0a	; char $45 HERE      OLD
!byte $00,$00,$80,$80,$80,$00,$00,$80	; char $46 HERE      OLD
!byte $7d,$7d,$7d,$7d,$7d,$7d,$7d,$7d	; char $47 HERE      OLD
!byte $6a,$a9,$6a,$a9,$6a,$a9,$6a,$a9	; char $48 HERE      OLD
!byte $00,$00,$00,$00,$00,$00,$00,$02	; char $49 HERE      OLD
!byte $0a,$28,$28,$20,$a0,$a0,$a0,$80	; char $4a HERE      OLD
!byte $80,$00,$00,$00,$00,$00,$00,$00	; char $4b HERE      OLD
!byte $7d,$7d,$7a,$6a,$6a,$aa,$aa,$a9	; char $4c HERE      OLD
!byte $fa,$aa,$aa,$a9,$a9,$a9,$aa,$9a	; char $4d HERE      OLD
!byte $aa,$96,$41,$00,$00,$00,$41,$96	; char $4e HERE      OLD
!byte $af,$aa,$aa,$6a,$6a,$6a,$aa,$99	; char $4f HERE      OLD
!byte $75,$5d,$a5,$a9,$a9,$aa,$aa,$aa	; char $50 HERE      OLD
!byte $02,$0a,$0a,$2a,$a8,$a8,$a0,$90	; char $51 HERE      OLD
!byte $02,$02,$02,$02,$02,$02,$02,$02	; char $52 HERE      OLD
!byte $a5,$95,$a5,$9d,$b5,$5d,$75,$5d	; char $53 HERE      OLD
!byte $56,$dd,$76,$dd,$75,$dd,$76,$dd	; char $54 HERE      OLD
!byte $aa,$aa,$55,$96,$aa,$69,$55,$aa	; char $55 HERE      OLD
!byte $55,$5d,$b7,$9d,$77,$5d,$b7,$9d	; char $56 HERE      OLD
!byte $5a,$5a,$56,$75,$5d,$75,$7d,$7d	; char $57 HERE      OLD
!byte $80,$40,$40,$00,$00,$00,$00,$00	; char $58 HERE      OLD
!byte $02,$02,$02,$02,$0e,$0e,$0a,$0a	; char $59 HERE      OLD
!byte $7d,$7d,$7d,$7d,$7d,$55,$7d,$7d	; char $5a HERE      OLD
!byte $69,$55,$96,$aa,$69,$55,$96,$aa	; char $5b HERE      OLD
!byte $0b,$08,$08,$08,$08,$08,$38,$a8	; char $5c HERE      OLD
!byte $69,$55,$96,$aa,$69,$55,$96,$eb	; char $5d HERE      OLD
!byte $a8,$28,$28,$88,$88,$38,$2c,$00	; char $5e HERE      OLD
!byte $57,$5f,$5e,$7a,$7a,$6a,$6a,$ea	; char $5f HERE      OLD
!byte $7d,$96,$aa,$aa,$aa,$aa,$96,$96	; char $60 HERE      OLD
!byte $d5,$b5,$b5,$ad,$ad,$a9,$a9,$ab	; char $61 HERE      OLD
!byte $ff,$00,$00,$00,$00,$00,$00,$ff	; char $62      PREV OLD
!byte $55,$5d,$75,$5d,$75,$5d,$75,$5d	; char $63 HERE      OLD
!byte $75,$5d,$75,$5d,$75,$5d,$75,$5d	; char $64 HERE      OLD
!byte $3c,$ef,$ab,$aa,$ee,$22,$aa,$bb	; char $65 HERE      OLD
!byte $75,$5d,$75,$5d,$75,$5d,$75,$55	; char $66 HERE      OLD
!byte $fc,$00,$cf,$bb,$ec,$30,$00,$00	; char $67 HERE      OLD
!byte $00,$03,$03,$02,$02,$02,$02,$03	; char $68 HERE      OLD
!byte $eb,$aa,$aa,$3c,$3c,$aa,$be,$aa	; char $69 HERE      
!byte $00,$c0,$c0,$80,$80,$80,$80,$c0	; char $6a HERE      
!byte $20,$a8,$20,$20,$a8,$20,$20,$a8	; char $6b HERE      
!byte $c3,$82,$be,$eb,$3c,$00,$00,$00	; char $6c HERE      
!byte $22,$aa,$aa,$22,$00,$00,$00,$00	; char $6d HERE      
