!byte $00,$00,$00,$00,$00,$00,$00,$00	; char $ 0 HERE PREV OLD
!byte $80,$c0,$e0,$f0,$f8,$fc,$fe,$ff	; char $ 1 HERE PREV 
!byte $c0,$60,$38,$0e,$18,$30,$1e,$07	; char $ 2      PREV 
!byte $ff,$7f,$3f,$1f,$0f,$07,$03,$01	; char $ 3      PREV 
!byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$80	; char $ 4 HERE PREV 
!byte $00,$18,$3c,$7e,$7e,$3c,$18,$00	; char $ 5      PREV 
!byte $03,$06,$0c,$06,$23,$36,$7c,$c8	; char $ 6      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff	; char $ 7 HERE PREV 
!byte $80,$c0,$60,$30,$1e,$36,$72,$c9	; char $ 8      PREV 
!byte $01,$03,$07,$0f,$1f,$3f,$7f,$ff	; char $ 9 HERE PREV 
!byte $01,$03,$06,$2c,$7c,$86,$ca,$91	; char $ a      PREV 
!byte $aa,$aa,$aa,$bf,$bf,$bf,$bf,$bf	; char $ b      PREV 
!byte $aa,$aa,$aa,$ff,$ff,$ff,$ff,$ff	; char $ c      PREV 
!byte $a9,$a9,$a9,$fd,$fd,$fd,$fd,$fd	; char $ d      PREV 
!byte $bf,$bf,$bf,$bf,$bf,$bf,$bf,$bf	; char $ e      PREV 
!byte $aa,$aa,$aa,$80,$80,$80,$80,$80	; char $ f      PREV 
!byte $aa,$aa,$aa,$00,$00,$00,$00,$00	; char $10      PREV 
!byte $5f,$6f,$6f,$2f,$2f,$2f,$2f,$2f	; char $11      PREV 
!byte $55,$56,$56,$42,$42,$42,$42,$42	; char $12      PREV 
!byte $fa,$fa,$fa,$f8,$f8,$f8,$f8,$f8	; char $13      PREV 
!byte $55,$56,$56,$02,$02,$02,$02,$02	; char $14      PREV 
!byte $fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe	; char $15      PREV 
!byte $80,$80,$80,$80,$80,$80,$80,$80	; char $16 HERE PREV 
!byte $af,$af,$af,$ff,$ff,$ff,$ff,$ff	; char $17      PREV 
!byte $2f,$2f,$2f,$2f,$2f,$2f,$2f,$2f	; char $18      PREV 
!byte $bf,$bf,$bf,$bf,$bf,$aa,$aa,$aa	; char $19      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$5f,$6f,$6f	; char $1a      PREV 
!byte $40,$40,$40,$40,$40,$5a,$6a,$aa	; char $1b      PREV 
!byte $00,$00,$00,$00,$00,$02,$02,$02	; char $1c      PREV 
!byte $2f,$2f,$2f,$2f,$2f,$af,$af,$af	; char $1d      PREV 
!byte $42,$42,$42,$42,$42,$42,$42,$42	; char $1e      PREV 
!byte $f8,$f8,$f8,$f8,$f8,$f8,$f8,$f8	; char $1f      PREV 
!byte $00,$00,$00,$00,$00,$0a,$0a,$0a	; char $20      PREV 
!byte $02,$02,$02,$02,$02,$aa,$aa,$aa	; char $21      PREV 
!byte $00,$00,$00,$00,$00,$a9,$a5,$95	; char $22      PREV 
!byte $02,$02,$02,$02,$02,$02,$02,$02	; char $23      PREV 
!byte $0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b	; char $24      PREV 
!byte $bd,$bd,$bd,$bd,$bd,$bd,$bd,$bd	; char $25      PREV 
!byte $bd,$bd,$bd,$bd,$bd,$a5,$95,$55	; char $26      PREV 
!byte $fe,$fe,$fe,$fe,$fe,$aa,$aa,$aa	; char $27      PREV 
!byte $0b,$0b,$0b,$0b,$0b,$0a,$09,$05	; char $28      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$55,$56,$56	; char $29      PREV 
!byte $40,$40,$40,$40,$40,$6a,$6a,$aa	; char $2a      PREV 
!byte $00,$00,$00,$00,$00,$aa,$aa,$aa	; char $2b      PREV 
!byte $42,$42,$42,$42,$42,$6a,$6a,$aa	; char $2c      PREV 
!byte $f4,$f4,$f4,$f4,$f4,$f6,$f6,$fa	; char $2d      PREV 
!byte $bf,$bf,$bf,$bf,$bf,$55,$55,$55	; char $2e      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$aa,$aa,$aa	; char $2f      PREV 
!byte $00,$01,$03,$07,$0f,$1f,$3f,$7f	; char $30      PREV 
!byte $7f,$7f,$7f,$7f,$7f,$7f,$7f,$7f	; char $31      PREV 
!byte $7f,$3f,$1f,$0f,$0f,$1f,$3f,$7f	; char $32      PREV 
!byte $0f,$0f,$0f,$0f,$0f,$0f,$0f,$0f	; char $33      PREV 
!byte $80,$c0,$e0,$f0,$f0,$e0,$c0,$80	; char $34      PREV 
!byte $ff,$ff,$ff,$ff,$ff,$ef,$cf,$8f	; char $35      PREV 
!byte $7f,$3f,$1f,$0f,$07,$03,$01,$00	; char $36      PREV 
!byte $7f,$7f,$7e,$7c,$78,$70,$60,$40	; char $37      PREV 
!byte $ff,$ff,$7f,$3f,$1f,$0f,$07,$03	; char $38      PREV 
!byte $0f,$0f,$0f,$0f,$0f,$0e,$0c,$08	; char $39      PREV 
!byte $fe,$fc,$f8,$f0,$e0,$c0,$80,$00	; char $3a      PREV 
!byte $bb,$99,$99,$ff,$bb,$99,$99,$ff	; char $3b HERE      
!byte $01,$02,$04,$08,$10,$20,$40,$80	; char $3c HERE      
!byte $ab,$af,$bf,$ff,$bf,$af,$ab,$aa	; char $3d HERE      
!byte $ff,$ff,$fe,$fb,$be,$bb,$ee,$ba	; char $3e HERE      
!byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$ff	; char $3f HERE      
!byte $00,$00,$00,$00,$00,$00,$00,$ff	; char $40 HERE      
!byte $01,$03,$03,$13,$32,$30,$30,$20	; char $41 HERE      
!byte $aa,$ea,$fa,$fe,$ff,$fe,$fa,$ea	; char $42 HERE      
!byte $80,$80,$80,$80,$be,$9c,$9c,$9c	; char $43 HERE      
!byte $00,$00,$00,$00,$3e,$1c,$1c,$1c	; char $44 HERE      
!byte $81,$83,$83,$93,$b2,$b0,$b0,$a0	; char $45 HERE      
!byte $9a,$9a,$9a,$5a,$5a,$5a,$5a,$5a	; char $46 HERE      
!byte $9a,$9a,$5a,$5a,$5a,$5a,$5a,$5a	; char $47 HERE      
!byte $aa,$aa,$aa,$aa,$aa,$ab,$af,$bf	; char $48 HERE      
!byte $aa,$ab,$af,$bf,$ff,$ff,$ff,$ff	; char $49 HERE      
!byte $01,$02,$04,$08,$10,$20,$40,$ff	; char $4a HERE      
!byte $ff,$80,$80,$80,$80,$80,$80,$80	; char $4b HERE      
!byte $5a,$5a,$5a,$5a,$5a,$5a,$5a,$5a	; char $4c HERE      
!byte $80,$80,$80,$80,$80,$80,$80,$ff	; char $4d HERE      
!byte $55,$55,$15,$15,$15,$51,$51,$51	; char $4e HERE      
!byte $76,$25,$25,$04,$04,$54,$55,$75	; char $4f HERE      
!byte $db,$4b,$4b,$43,$43,$53,$53,$5b	; char $50 HERE      
!byte $ff,$af,$2f,$5f,$af,$9f,$af,$bf	; char $51 HERE      
!byte $ab,$8b,$97,$ab,$a3,$eb,$8b,$ab	; char $52 HERE      
!byte $ff,$ea,$e2,$e5,$ea,$f8,$e2,$ea	; char $53 HERE      
!byte $ff,$fa,$f8,$f9,$fa,$fa,$fe,$fa	; char $54 HERE      
!byte $ff,$be,$be,$7e,$bf,$3e,$be,$be	; char $55 HERE      
!byte $ff,$bf,$bf,$8f,$cf,$ef,$ef,$eb	; char $56 HERE      
!byte $ab,$ab,$ef,$ef,$ef,$ef,$ef,$eb	; char $57 HERE      
!byte $ea,$ea,$ea,$fb,$fb,$ce,$ef,$eb	; char $58 HERE      
!byte $f8,$fa,$fa,$fa,$ee,$ce,$ef,$eb	; char $59 HERE      
!byte $be,$be,$bb,$fb,$fb,$ba,$ff,$ff	; char $5a HERE      
!byte $ff,$00,$00,$00,$00,$00,$00,$ff	; char $5b HERE      
!byte $84,$3c,$3c,$3c,$3c,$3c,$3c,$84	; char $5c HERE      
!byte $81,$e7,$e7,$e7,$e7,$e7,$e7,$e7	; char $5d HERE      
!byte $33,$33,$33,$83,$f3,$33,$33,$87	; char $5e HERE      
!byte $ff,$03,$05,$09,$11,$21,$41,$81	; char $5f HERE      
!byte $bf,$af,$ab,$aa,$aa,$aa,$aa,$aa	; char $60 HERE      
!byte $fe,$fa,$ea,$aa,$aa,$aa,$aa,$aa	; char $61 HERE      
!byte $81,$81,$81,$81,$81,$81,$81,$81	; char $62 HERE      
!byte $aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa	; char $63 HERE      
!byte $ff,$00,$00,$00,$00,$00,$00,$00	; char $64 HERE      
!byte $01,$01,$01,$01,$01,$01,$01,$01	; char $65 HERE      
