!byte $00,$00,$00,$00,$00,$00,$00,$00	; char $ 0 HERE      OLD
!byte $80,$c0,$e0,$f0,$f8,$fc,$fe,$ff	; char $ 1 HERE      
!byte $c0,$60,$38,$0e,$18,$30,$1e,$07	; char $ 2 HERE      
!byte $ff,$7f,$3f,$1f,$0f,$07,$03,$01	; char $ 3 HERE      
!byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$80	; char $ 4 HERE      
!byte $00,$18,$3c,$7e,$7e,$3c,$18,$00	; char $ 5 HERE      
!byte $03,$06,$0c,$06,$23,$36,$7c,$c8	; char $ 6 HERE      
!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff	; char $ 7 HERE      
!byte $80,$c0,$60,$30,$1e,$36,$72,$c9	; char $ 8 HERE      
!byte $01,$03,$07,$0f,$1f,$3f,$7f,$ff	; char $ 9 HERE      
!byte $01,$03,$06,$2c,$7c,$86,$ca,$91	; char $ a HERE      
!byte $aa,$aa,$aa,$bf,$bf,$bf,$bf,$bf	; char $ b HERE      
!byte $aa,$aa,$aa,$ff,$ff,$ff,$ff,$ff	; char $ c HERE      
!byte $a9,$a9,$a9,$fd,$fd,$fd,$fd,$fd	; char $ d HERE      
!byte $bf,$bf,$bf,$bf,$bf,$bf,$bf,$bf	; char $ e HERE      
!byte $aa,$aa,$aa,$80,$80,$80,$80,$80	; char $ f HERE      
!byte $aa,$aa,$aa,$00,$00,$00,$00,$00	; char $10 HERE      
!byte $5f,$6f,$6f,$2f,$2f,$2f,$2f,$2f	; char $11 HERE      
!byte $55,$56,$56,$42,$42,$42,$42,$42	; char $12 HERE      
!byte $fa,$fa,$fa,$f8,$f8,$f8,$f8,$f8	; char $13 HERE      
!byte $55,$56,$56,$02,$02,$02,$02,$02	; char $14 HERE      
!byte $fe,$fe,$fe,$fe,$fe,$fe,$fe,$fe	; char $15 HERE      
!byte $80,$80,$80,$80,$80,$80,$80,$80	; char $16 HERE      
!byte $af,$af,$af,$ff,$ff,$ff,$ff,$ff	; char $17 HERE      
!byte $2f,$2f,$2f,$2f,$2f,$2f,$2f,$2f	; char $18 HERE      
!byte $bf,$bf,$bf,$bf,$bf,$aa,$aa,$aa	; char $19 HERE      
!byte $ff,$ff,$ff,$ff,$ff,$5f,$6f,$6f	; char $1a HERE      
!byte $40,$40,$40,$40,$40,$5a,$6a,$aa	; char $1b HERE      
!byte $00,$00,$00,$00,$00,$02,$02,$02	; char $1c HERE      
!byte $2f,$2f,$2f,$2f,$2f,$af,$af,$af	; char $1d HERE      
!byte $42,$42,$42,$42,$42,$42,$42,$42	; char $1e HERE      
!byte $f8,$f8,$f8,$f8,$f8,$f8,$f8,$f8	; char $1f HERE      
!byte $00,$00,$00,$00,$00,$0a,$0a,$0a	; char $20 HERE      
!byte $02,$02,$02,$02,$02,$aa,$aa,$aa	; char $21 HERE      
!byte $00,$00,$00,$00,$00,$a9,$a5,$95	; char $22 HERE      
!byte $02,$02,$02,$02,$02,$02,$02,$02	; char $23 HERE      
!byte $0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b	; char $24 HERE      
!byte $bd,$bd,$bd,$bd,$bd,$bd,$bd,$bd	; char $25 HERE      
!byte $bd,$bd,$bd,$bd,$bd,$a5,$95,$55	; char $26 HERE      
!byte $fe,$fe,$fe,$fe,$fe,$aa,$aa,$aa	; char $27 HERE      
!byte $0b,$0b,$0b,$0b,$0b,$0a,$09,$05	; char $28 HERE      
!byte $ff,$ff,$ff,$ff,$ff,$55,$56,$56	; char $29 HERE      
!byte $40,$40,$40,$40,$40,$6a,$6a,$aa	; char $2a HERE      
!byte $00,$00,$00,$00,$00,$aa,$aa,$aa	; char $2b HERE      
!byte $42,$42,$42,$42,$42,$6a,$6a,$aa	; char $2c HERE      
!byte $f4,$f4,$f4,$f4,$f4,$f6,$f6,$fa	; char $2d HERE      
!byte $bf,$bf,$bf,$bf,$bf,$55,$55,$55	; char $2e HERE      
!byte $ff,$ff,$ff,$ff,$ff,$aa,$aa,$aa	; char $2f HERE      
!byte $00,$01,$03,$07,$0f,$1f,$3f,$7f	; char $30 HERE      
!byte $7f,$7f,$7f,$7f,$7f,$7f,$7f,$7f	; char $31 HERE      
!byte $7f,$3f,$1f,$0f,$0f,$1f,$3f,$7f	; char $32 HERE      
!byte $0f,$0f,$0f,$0f,$0f,$0f,$0f,$0f	; char $33 HERE      
!byte $80,$c0,$e0,$f0,$f0,$e0,$c0,$80	; char $34 HERE      
!byte $ff,$ff,$ff,$ff,$ff,$ef,$cf,$8f	; char $35 HERE      
!byte $7f,$3f,$1f,$0f,$07,$03,$01,$00	; char $36 HERE      
!byte $7f,$7f,$7e,$7c,$78,$70,$60,$40	; char $37 HERE      
!byte $ff,$ff,$7f,$3f,$1f,$0f,$07,$03	; char $38 HERE      
!byte $0f,$0f,$0f,$0f,$0f,$0e,$0c,$08	; char $39 HERE      
!byte $fe,$fc,$f8,$f0,$e0,$c0,$80,$00	; char $3a HERE      
